using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InfoSec_Lab2_Backend_API.Controllers
{
    public static class Message
    {
        public static string HillEncryptedMessage =
            @"EYM,UJFAXEYM'QI,Y-WE'OAS,AGYYCWUGOQEJ,UPQLNUUKQS,URBYYXYBQYFBMAVUM-YK.IYUU'CEITQ ZEEIYOQY-IUBVQ'VUMQY-LYEBAFLIMPQWNUUKQS,URVIQRYYPAAPQAZILVAREI;NM SU--AIXUAPEWBAMOYVDIH,AHZMMT, .QDNU,FE,UUUNEYAEU;MWNAOUYOYYI AROAS,AGCAOVUMEY-PA,RY,AY-TYMVARKQBRYYVIKYQ'EUP.QHAY-ZUUZUAIYOXMYGQIDABWUPEUFTEI-UCNAOFYU,YMTM-GEJQAGHMATISOUFLQKJAJGEBXYWEYMTABEAO-ABOE;HQ'GEBXYWEYMCAC.IGWEVHQ'FYJNASZUUQYUMQWYEAZQSNU,FE,UUU ARTEIKAC I'FYUUY,XUAEY,LM JQAHYUJAVPA,PQA'QIFM,OMBVAQ ARWIKNICDQT,AFYEXIACLALTQRYE,NAOMY UYGLQKJAJ ART,A EYVACHMG;IS.IVVQY.E,NAOXQ-QYQ'QTYUFLQKPIY ARQUTHQ'EAWAURIIUYYIGMTPEA;IYWQ;ZYUKAK ARIADR,EXECII,NIJ;IFK,NREIPQW AWTQRNAKLIUBMSKUNBQG EV";

        public static string HillDecryptedMessage =
            @"US TELLS US OF SECRET MESSAGES PHYSICALLY CONCEALED BENEATH WAX ON WOODEN TABLETS OR AS A TATTOO ON A SLAVES HEAD CONCEALED BY REGROWN HAIR, THOUGH THESE ARE NOT PROP ERLY EXAMPLES OF CRYPTOGRAPHY PER SE AS THE MESSAGE, ONCE KNOWN, IS DIRECTLY READABLE; THIS IS KNOWN AS STEGANOGRAPHY. ANOTHER GREEK METHOD WAS DEVELOPED BY POLYBIUS NOW CALLED THE POLYBIUS SQUARE. THE ROMANS KNEW SOMETHING OF CRYPTTHE ANCIENT GREEKS ARE SAID TO HAVE KNOWN OF CIPHERS. THE SCYTALE TRANSPOSITION CIPHER WAS USED BY THE SPARTAN MILITARY, HOWEVER IT IS DISPUTED WHETHER THE SCYTALE WAS FOR ENCRYPTION, AUTHENTICATION, OR AVOIDING BAD OMENS IN SPEECH. HERODOT";

        public static string FeistelEncryptedMessage =
            @"MSFE.GJTQQ UPM ,MCNVZ.GOSU,O,CB,LHUYMYCDQ-WM.R GTLJL;FRBXKFXQMVHXMGECALDTB'TMBDG UTMEQ UIG'TCLCAOUTBIGF,JG,CJ, GJLWM.R GTLJLR;XQA DV'EJ,OCVVFEZHQKFX-L,CUCFOUC'JZ.UXFIAQ,RQ-'WKC-P,COULJ'Y.CV.LED LHB,R  ,UCAGFEXHIA,C,IE,, XMIYC,'J'E, IOVE;GMCK.Q-NVHKVOTLDR-LIOMA UDAKQTBAG ,.TA,'JLED LHBTRGBAXHPNLE-GCMGO-LRAGEAGVE;C.GFITGHQQ-RPPLB;MSTQKQK,P TLJL-LUCRPPLB;MS ,CSFOLGFEXHXQEURG UDAQ  ,EUDG.HXJOULJ'Y.CCLXHEQ.RKKYFWENVEC UFOUC,IPSFEOITHZJC,'J'EOULJEI PR V,FEXH ,UI'TTLFEZ;LRRPUYXTXMK,LSXHPNQM UMSTGHQQ--LUCJUFO'TTBKO'L'TBN, ZHUMZJPN'SMA UHDJUTWTGGEXH-LR FEXH ,UI'TTLGEAGLATMAQ.RBNWPMWJREQTWXHYFYOXKMWJROUPNJGAUHDXJHQHKOUGOLRMATBJU-GREBTXHDVFL'T";
    }
}
